title: Asfina Hassan Juicy
description: Welcome! I am a recent graduate in biomedical engineering, and this section provides a brief overview of some of my academic research and projects from my undergraduate studies.
show_downloads: false

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
