title: Asfina Hassan Juicy
description: I have recently completed my undergraduation in Biomedical Engineering from Bangladesh University of Engineering and Technology(BUET), Dhaka, Bangladesh. This section provides a brief overview of some of my academic research experiences and projects from my undergraduate studies.
show_downloads: false

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
