title: Asfina Hassan Juicy # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Biomedical Engineering Graduate
  <br><br>
  **Research Interests**
  <br><br>
  - Biomedical Image Processing
  - Deep Learning in Healthcare
  - AI in Healthcare
  - Biomedical Sensors
  - Biomedical Signal Processing
  - Biomedical Instrumentation
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
